pipeline:
  create-build-image:
    image: docker
    commands:
      - docker build --target build -t ${DRONE_REPO,,}:${DRONE_BUILD_NUMBER} .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pre-test:
    image: "${DRONE_REPO,,}:${DRONE_BUILD_NUMBER}"
    commands:
      - cp `which node` /drone/node
      - cp `which yarn` /drone/yarn

  test:
    image: microadam/graphicsmagick-alpine:1.3.23
    commands:
      - export PATH=/drone:$PATH
      - yarn test

  compile-app:
    image: "${DRONE_REPO,,}:${DRONE_BUILD_NUMBER}"
    environment:
      - PKG_CACHE_PATH=/drone/pkg-cache
    commands:
      - mv locations.js.env locations.js
      - pkg -t host app.js -o darkoom

  publish-release-image:
    image: docker
    commands:
      - echo "$GOOGLE_CREDENTIALS" | docker login -u _json_key --password-stdin https://eu.gcr.io
      - docker build --target release -t eu.gcr.io/test-k8s-1289/darkroom:${DRONE_COMMIT_SHA} .
      - docker push eu.gcr.io/test-k8s-1289/darkroom:${DRONE_COMMIT_SHA}
      - docker rmi eu.gcr.io/test-k8s-1289/darkroom:${DRONE_COMMIT_SHA}
    secrets: [ google_credentials ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  delete-previous-build-image:
    image: docker
    commands:
      - docker rmi -f ${DRONE_REPO,,}:${DRONE_PREV_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [ success, failure ]

  notify:
    image: plugins/slack
    channel: adam-test
    username: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
